name: Hunters
main: Savion\Main
version: 1.0_BETA
api: [1.12.0]
load: POSTWORLD
author: SavionLegendZzz
commands:
 h:
  permission: hunters.command.hunters
  description: hunters command
  usage: /h <setgame|remove>
